// <auto-generated>
// Rewired Constants
// This list was generated on 11/07/2020 6:48:41 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace GMTK2020.Controls {
    public static partial class Action {
        // Default
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVERTICAL")]
        public const int UIVERTICAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHORIZONTAL")]
        public const int UIHORIZONTAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISUBMIT")]
        public const int UISUBMIT = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICANCEL")]
        public const int UICANCEL = 3;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "MainPlayer")]
        public const int MAINPLAYER = 0;
    }
}
